
[functions.send-transactional-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-transactional-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-transactional-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-transactional-email/*.html" ]

[functions.send-affiliate-notification]
enabled = true
verify_jwt = true
import_map = "./functions/send-affiliate-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-affiliate-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-affiliate-notification/*.html" ]

[functions.sync-affiliate-billing]
enabled = true
verify_jwt = true
entrypoint = "./functions/sync-affiliate-billing/index.ts"
